#!/bin/sh

#  ┏┓┳┓┏┓┏┓┳┓ ┏┓
#  ┃┃┣┫┃┃┣ ┃┃ ┣
#  ┣┛┛┗┗┛┻ ┻┗┛┗┛
#
#  ┓ ┏┓┳┳┳┓┏┓┓┏  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓  ┓ ┳┓┏┓┏┓  ┏┓  ┏┓┓┏┏┓┳┓
#  ┃ ┣┫┃┃┃┃┃ ┣┫  ┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃  ┃ ┃┃┫ ┣   ┣┫  ┃ ┣┫┣┫┃┃
#  ┗┛┛┗┗┛┛┗┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛  ┗┛┻┛┗┛┗┛  ┛┗  ┗┛┛┗┛┗┻┛
#


# shellcheck disable=SC2155

# Profile file, runs on login. Environmental variables are set here.

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

# Variables
export EDITOR="nvim"
export TERMINAL="foot"
export BROWSER="firefox"

# Home cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# Spicetify
export PATH="$PATH:$HOME/.spicetify"


#  ┓ ┏┓┳┳┳┓┏┓┓┏  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃ ┣┫┃┃┃┃┃ ┣┫  ┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┗┛┛┗┗┛┛┗┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                
# Starting Wayland
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  dbus-launch Hyprland
fi
